services:
  backend:
    build:
      context: .
      dockerfile: backend/dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
      - NODE_ENV=development

  frontend:
    build:
      context: .
      dockerfile: frontend/dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    working_dir: /app/frontend
    volumes: # this is for hot reload, we map our local files inside conteiner
      - ./frontend:/app/frontend
      - /app/node_modules # and this overwrites containers modules over our mapped file
    depends_on:
      - backend
    environment:
      - VITE_PORT=3000
      - VITE_API_PROXY_TARGET=http://backend:5000
