FROM node:24-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY backend/package.json ./backend/
COPY frontend/package.json ./frontend/
COPY packages/types ./packages/types/

RUN npm ci

COPY backend ./backend

WORKDIR /app/backend

EXPOSE 5000

CMD ["npm", "run", "dev"]
