import type { AuditRouteRule } from "./audit.types.js";

export const auditRouteRules: AuditRouteRule[] = [
  {
    action: "adoption_application.create",
    entityType: "adoption_application",
    method: "POST",
    path: "/api/adoption-applications",
  },
  {
    action: "adoption_application.status_update",
    entityIdParam: "id",
    entityType: "adoption_application",
    method: "PATCH",
    path: "/api/adoption-applications/:id/status",
  },
  {
    action: "pet.create",
    entityType: "pet",
    method: "POST",
    path: "/api/pets",
  },
  {
    action: "pet.walk_record",
    entityIdParam: "id",
    entityType: "pet",
    method: "POST",
    path: "/api/pets/:id/walks",
  },
  {
    action: "pet.photo_upload",
    entityIdParam: "id",
    entityType: "pet",
    method: "POST",
    path: "/api/pets/:id/photo",
  },
  {
    action: "pet.walk_cancel",
    entityIdParam: "walkId",
    entityType: "pet_walk",
    method: "DELETE",
    path: "/api/pets/walks/:walkId",
  },
  {
    action: "pet.delete",
    entityIdParam: "id",
    entityType: "pet",
    method: "DELETE",
    path: "/api/pets/:id",
  },
  {
    action: "medical_event.create",
    entityType: "medical_event",
    method: "POST",
    path: "/api/medical-schedule",
  },
  {
    action: "medical_event.update",
    entityIdParam: "id",
    entityType: "medical_event",
    method: "PATCH",
    path: "/api/medical-schedule/:id",
  },
  {
    action: "medical_event.cancel",
    entityIdParam: "id",
    entityType: "medical_event",
    method: "DELETE",
    path: "/api/medical-schedule/:id",
  },
  {
    action: "medical_reminder.run",
    entityType: "medical_event_reminder",
    method: "POST",
    path: "/api/medical-schedule/reminders/run",
  },
  {
    action: "audit_action_setting.update",
    entityIdParam: "action",
    entityType: "audit_action_setting",
    method: "PATCH",
    path: "/api/audit-logs/actions/:action",
    skipActionSettingCheck: true,
  },
  {
    action: "volunteer.create",
    entityType: "volunteer",
    method: "POST",
    path: "/api/volunteers",
  },
  {
    action: "volunteer.update",
    entityIdParam: "id",
    entityType: "volunteer",
    method: "PATCH",
    path: "/api/volunteers/:id",
  },
  {
    action: "volunteer.delete",
    entityIdParam: "id",
    entityType: "volunteer",
    method: "DELETE",
    path: "/api/volunteers/:id",
  },
];
