


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."pets" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL,
    "species" character varying NOT NULL,
    "weight" integer,
    "description" "text" NOT NULL,
    "age" integer,
    "breed" "text",
    "size" "text",
    "image_url" "text"
);


ALTER TABLE "public"."pets" OWNER TO "postgres";


ALTER TABLE "public"."pets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Pets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."adoption_applications" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "pet_id" bigint NOT NULL,
    "user_id" "uuid",
    "full_name" "text" NOT NULL,
    "email" "text" NOT NULL,
    "phone" "text",
    "city" "text",
    "housing_type" "text",
    "has_other_pets" boolean,
    "message" "text" NOT NULL,
    "status" "text" DEFAULT 'new'::"text" NOT NULL,
    CONSTRAINT "adoption_applications_status_check" CHECK (("status" = ANY (ARRAY['new'::"text", 'reviewing'::"text", 'accepted'::"text", 'rejected'::"text"])))
);


ALTER TABLE "public"."adoption_applications" OWNER TO "postgres";


ALTER TABLE "public"."adoption_applications" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."adoption_applications_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."audit_logs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "actor_user_id" "uuid",
    "actor_email" "text",
    "action" "text" NOT NULL,
    "entity_type" "text" NOT NULL,
    "entity_id" "text",
    "route" "text" NOT NULL,
    "method" "text" NOT NULL,
    "ip_address" "text",
    "user_agent" "text",
    "metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "old_data" "jsonb",
    "new_data" "jsonb"
);


ALTER TABLE "public"."audit_logs" OWNER TO "postgres";


ALTER TABLE "public"."audit_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."audit_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pet_walks" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "pet_id" bigint NOT NULL,
    "walker_id" "uuid",
    "walked_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "notes" "text"
);


ALTER TABLE "public"."pet_walks" OWNER TO "postgres";


ALTER TABLE "public"."pet_walks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pet_walks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."pets"
    ADD CONSTRAINT "Pets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."adoption_applications"
    ADD CONSTRAINT "adoption_applications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."audit_logs"
    ADD CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pet_walks"
    ADD CONSTRAINT "pet_walks_pkey" PRIMARY KEY ("id");



CREATE INDEX "adoption_applications_pet_id_idx" ON "public"."adoption_applications" USING "btree" ("pet_id");



CREATE INDEX "adoption_applications_status_idx" ON "public"."adoption_applications" USING "btree" ("status");



CREATE INDEX "adoption_applications_user_id_idx" ON "public"."adoption_applications" USING "btree" ("user_id");



CREATE INDEX "audit_logs_action_idx" ON "public"."audit_logs" USING "btree" ("action");



CREATE INDEX "audit_logs_actor_user_id_idx" ON "public"."audit_logs" USING "btree" ("actor_user_id");



CREATE INDEX "audit_logs_created_at_idx" ON "public"."audit_logs" USING "btree" ("created_at" DESC);



CREATE INDEX "audit_logs_entity_idx" ON "public"."audit_logs" USING "btree" ("entity_type", "entity_id");



CREATE INDEX "pet_walks_pet_id_idx" ON "public"."pet_walks" USING "btree" ("pet_id");



CREATE INDEX "pet_walks_pet_id_walked_at_idx" ON "public"."pet_walks" USING "btree" ("pet_id", "walked_at" DESC);



CREATE INDEX "pet_walks_walked_at_idx" ON "public"."pet_walks" USING "btree" ("walked_at" DESC);



ALTER TABLE ONLY "public"."adoption_applications"
    ADD CONSTRAINT "adoption_applications_pet_id_fkey" FOREIGN KEY ("pet_id") REFERENCES "public"."pets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."adoption_applications"
    ADD CONSTRAINT "adoption_applications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."audit_logs"
    ADD CONSTRAINT "audit_logs_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."pet_walks"
    ADD CONSTRAINT "pet_walks_pet_id_fkey" FOREIGN KEY ("pet_id") REFERENCES "public"."pets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pet_walks"
    ADD CONSTRAINT "pet_walks_walker_id_fkey" FOREIGN KEY ("walker_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



CREATE POLICY "Enable read access for all users" ON "public"."pets" FOR SELECT USING (true);



ALTER TABLE "public"."adoption_applications" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."audit_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pet_walks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pets" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





































































































































































GRANT ALL ON TABLE "public"."pets" TO "anon";
GRANT ALL ON TABLE "public"."pets" TO "authenticated";
GRANT ALL ON TABLE "public"."pets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Pets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Pets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Pets_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."adoption_applications" TO "anon";
GRANT ALL ON TABLE "public"."adoption_applications" TO "authenticated";
GRANT ALL ON TABLE "public"."adoption_applications" TO "service_role";



GRANT ALL ON SEQUENCE "public"."adoption_applications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."adoption_applications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."adoption_applications_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."audit_logs" TO "anon";
GRANT ALL ON TABLE "public"."audit_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."audit_logs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."audit_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."audit_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."audit_logs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pet_walks" TO "anon";
GRANT ALL ON TABLE "public"."pet_walks" TO "authenticated";
GRANT ALL ON TABLE "public"."pet_walks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pet_walks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pet_walks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pet_walks_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


