create table if not exists public.pet_walks (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  pet_id bigint not null references public.pets (id) on delete cascade,
  walker_id uuid references auth.users (id) on delete set null,
  walked_at timestamptz not null default now(),
  notes text
);

create index if not exists pet_walks_pet_id_idx
  on public.pet_walks (pet_id);

create index if not exists pet_walks_pet_id_walked_at_idx
  on public.pet_walks (pet_id, walked_at desc);

create index if not exists pet_walks_walked_at_idx
  on public.pet_walks (walked_at desc);