create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_user_id uuid references auth.users (id) on delete set null,
  actor_email text,
  action text not null,
  entity_type text not null,
  entity_id text,
  route text not null,
  method text not null,
  ip_address text,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  old_data jsonb,
  new_data jsonb
);

alter table public.audit_logs enable row level security;

create index if not exists audit_logs_actor_user_id_idx
  on public.audit_logs (actor_user_id);

create index if not exists audit_logs_action_idx
  on public.audit_logs (action);

create index if not exists audit_logs_entity_idx
  on public.audit_logs (entity_type, entity_id);

create index if not exists audit_logs_created_at_idx
  on public.audit_logs (created_at desc);
