create table if not exists public.adoption_applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  pet_id bigint not null references public.pets (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  full_name text not null,
  email text not null,
  phone text,
  city text,
  housing_type text,
  has_other_pets boolean,
  message text not null,
  status text not null default 'new' check (status in ('new', 'reviewing', 'accepted', 'rejected'))
);

alter table public.adoption_applications enable row level security;

create index if not exists adoption_applications_pet_id_idx
  on public.adoption_applications (pet_id);

create index if not exists adoption_applications_user_id_idx
  on public.adoption_applications (user_id);

create index if not exists adoption_applications_status_idx
  on public.adoption_applications (status);