create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  starts_at timestamptz not null,
  ends_at timestamptz,
  location text not null,
  event_type text not null default 'other' check (
    event_type in (
      'open_day',
      'food_drive',
      'volunteer_training',
      'community_event',
      'other'
    )
  ),
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.calendar_events enable row level security;

create policy "Public can read public calendar events"
  on public.calendar_events
  for select
  using (is_public = true);

create index if not exists calendar_events_public_starts_at_idx
  on public.calendar_events (starts_at)
  where is_public = true;

create index if not exists calendar_events_public_event_type_idx
  on public.calendar_events (event_type)
  where is_public = true;

insert into public.calendar_events (
  title,
  description,
  starts_at,
  ends_at,
  location,
  event_type,
  is_public
) values
  (
    'Weekend open day',
    'Meet adoptable dogs and cats, talk with staff, and submit a same-day application.',
    date_trunc('day', now()) + interval '4 days' + interval '10 hours',
    date_trunc('day', now()) + interval '4 days' + interval '14 hours',
    'Main shelter courtyard',
    'open_day',
    true
  ),
  (
    'Food drive collection',
    'Bring dry food, blankets, and treats to support the shelter pantry.',
    date_trunc('day', now()) + interval '13 days' + interval '9 hours',
    date_trunc('day', now()) + interval '13 days' + interval '12 hours',
    'Reception entrance',
    'food_drive',
    true
  ),
  (
    'Volunteer orientation evening',
    'Intro session for new volunteers with a short shelter tour and Q&A.',
    date_trunc('day', now()) + interval '23 days' + interval '17 hours 30 minutes',
    date_trunc('day', now()) + interval '23 days' + interval '19 hours',
    'Training room',
    'volunteer_training',
    true
  ),
  (
    'Summer adoption fair',
    'A public adoption fair with matchmakers, family activities, and pet meetups.',
    date_trunc('day', now()) + interval '47 days' + interval '11 hours',
    date_trunc('day', now()) + interval '47 days' + interval '15 hours',
    'City park pop-up tent',
    'community_event',
    true
  );