create table if not exists public.medical_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  pet_id bigint not null references public.pets (id) on delete cascade,
  type text not null check (type in ('vaccination', 'checkup', 'surgery', 'other')),
  title text not null,
  scheduled_at timestamptz not null,
  status text not null default 'scheduled' check (status in ('scheduled', 'completed', 'cancelled')),
  notes text,
  created_by uuid references auth.users (id) on delete set null,
  created_by_email text,
  reminder_sent_at timestamptz
);

create index if not exists medical_events_pet_id_idx
  on public.medical_events (pet_id);

create index if not exists medical_events_scheduled_at_idx
  on public.medical_events (scheduled_at);

create index if not exists medical_events_status_scheduled_at_idx
  on public.medical_events (status, scheduled_at);

alter table public.medical_events enable row level security;

create table if not exists public.medical_event_reminders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  medical_event_id bigint not null references public.medical_events (id) on delete cascade,
  audience_role text not null check (audience_role in ('admin', 'coordinator')),
  due_at timestamptz not null,
  read_at timestamptz,
  unique (medical_event_id, audience_role)
);

create index if not exists medical_event_reminders_due_at_idx
  on public.medical_event_reminders (due_at);

create index if not exists medical_event_reminders_role_due_at_idx
  on public.medical_event_reminders (audience_role, due_at);

alter table public.medical_event_reminders enable row level security;
